dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.90
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.90
- name: nodey43
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
